[package]
name = "wallpaper"
version = "0.1.0"
authors = ["reujab <reujab@gmail.com>"]

[target.'cfg(any(unix, windows))'.dependencies]
dirs = "1.0"
reqwest = "0.8"
url = "1.7"

[target.'cfg(unix)'.dependencies]
enquote = "1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
rust-ini = "0.12"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
